source 'https://github.com/CocoaPods/Specs.git'

version = '10.0'

platform :ios, version

$isSourceCode = 0
$CarthagePodsPath = "./CarthagePods/"
$CarthsSourceCodePath = './Carthage/Checkouts/'
def carthage_pods
  if $isSourceCode ==  0
    pod 'IGListKit', :path => $CarthagePodsPath
    pod 'IGListDiffKit', :path => $CarthagePodsPath
    pod 'AFNetworking', :path => $CarthagePodsPath
    pod 'SDWebImage', :path => $CarthagePodsPath
    pod 'libwebp', :path => $CarthagePodsPath
    pod 'SDWebImageWebPCoder', :path => $CarthagePodsPath
    pod 'lottie-ios', :path => $CarthagePodsPath
    pod 'RxSwift', :path => $CarthagePodsPath
    pod 'RxCocoa', :path => $CarthagePodsPath
    pod 'RxRelay', :path => $CarthagePodsPath
    pod 'MJRefresh', :path => $CarthagePodsPath
  else
    pod 'IGListKit', :path => $CarthsSourceCodePath + "IGListKit"
    pod 'IGListDiffKit', :path => $CarthsSourceCodePath + "IGListKit"
    pod 'AFNetworking', :path => $CarthsSourceCodePath + "AFNetworking"
    pod 'SDWebImage', :path => $CarthsSourceCodePath + "SDWebImage"
    pod 'libwebp', :path => $CarthsSourceCodePath + "libwebp-Xcode/libwebp"
    pod 'SDWebImageWebPCoder', :path => $CarthsSourceCodePath + "SDWebImageWebPCoder"
    pod 'lottie-ios', :path => $CarthsSourceCodePath + "lottie-ios"
    pod 'RxSwift', :path => $CarthsSourceCodePath + "RxSwift"
    pod 'RxCocoa', :path => $CarthsSourceCodePath + "RxSwift"
    pod 'RxRelay', :path => $CarthsSourceCodePath + "RxSwift"
    pod 'MJRefresh', :path => $CarthsSourceCodePath + "MJRefresh"
  end
end


target 'BuildStaticLibrary' do
  carthage_pods
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < version.to_f
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = version
      end
    end
  end
end
